export const pages = [
  {
    link: "/",
    title: "Home",
    description: "Filmhub",

    hero: {
      posters: [
        { name: "Black Cinema", img: "p1.jpg", alt: "Six Rounds", color: "#3ec2dd", isNew: true, },
        { name: "Climate change", img: "p2.jpg", alt: "Ice Motion", color: "#9685ce" },
        { name: "Women filmmakers", img: "p3.jpg", alt: "Aleksi", color: "#a5af29", isNew: true, },
        { name: "Aapi Filmmakers", img: "p4.jpg", alt: "Reunification", color: "#24c7ae" },
        { name: "Summertime", img: "p5.jpg", alt: "Loud Places", color: "#68abff" },
        { name: "Climate change", img: "p6.jpg", alt: "Endgame 2050", color: "#9685ce" },
        { name: "Neo-noir", img: "p7.jpg", alt: "Hello Gangster", color: "#ac9f92" },
        { name: "Black cinema", img: "p8.jpg", alt: "The Rise and Fall of Miss Thang", color: "#3ec2dd" },
        { name: "Soccer Films", img: "p9.jpg", alt: "Funke!", color: "#f25959" },
        { name: "AAPI Filmmakers", img: "p10.jpg", alt: "Love Arcadia", color: "#3ec2dd" },
        { name: "Climate Change", img: "p11.jpg", alt: "Earth Day", color: "#3ec2dd" },
        { name: "Black Cinema", img: "p12.jpg", alt: "Back to Natural", color: "#3ec2dd" },
        { name: "Neo-Noir", img: "p13.jpg", alt: "Motif", color: "#3ec2dd" },
        { name: "Soccer Films", img: "p14.jpg", alt: "Offside", color: "#f25959" },
        { name: "Summertime", img: "p15.jpg", alt: "Summertime in New York", color: "#68abff" },
        { name: "AAPI Filmmakers", img: "p16.jpg", alt: "The Crumbles", color: "#24c7ae" },
        { name: "Women Filmmakers", img: "p17.jpg", alt: "To the New Girl", color: "#a5af29" },
        { name: "Soccer Films", img: "p18.jpg", alt: "The Team", color: "#f25959" },
        { name: "Climate Change", img: "p19.jpg", alt: "Speechless: The Polar Realm", color: "#9685ce" },
        { name: "Neo-Noir", img: "p20.jpg", alt: "Why Siegfried Teitelbaum Had To Die", color: "#ac9f92" },
        { name: "Women Filmmakers", img: "p21.jpg", alt: "Wink", color: "#3ec2dd" },
        { name: "Summertime", img: "p22.jpg", alt: "The Beautiful Washing Machine", color: "#68abff" },
        { name: "Soccer Films", img: "p23.jpg", alt: "Street Soccer: New York", color: "#f25959" },
        { name: "Women Filmmakers", img: "p24.jpg", alt: "The Pink Chateau", color: "#a5af29" },
        { name: "Summertime", img: "p25.jpg", alt: "Xolo", color: "#68abff" },
      ]
    },
    cta: {
      title: "Channel buyers",
      description: "Interested in joining Filmhub’s roster of 100+ streaming channels licensing fresh, amazing cinema?",
      button: {
        name: "Let's talk",
        link: "#"
      }
    },
    customers: {
      title: "FILMMAKERS:<br /> Get your titles on streaming services including",
      description: "...and more",
      list: [
        {name: "Nuella TV", img: "nuella-tv.svg"},
        {name: "Christian Channel", img: "christian-channel.svg"},
        {name: "Filmzie", img: "filmzie.svg"},
        {name: "BingeHorror", img: "bingehorror.svg"},
        {name: "Vyre", img: "vyre.png"},
        {name: "Dekkoo", img: "dekkoo.svg"},
        {name: "Filmocracy", img: "filmocracy.svg"},
        {name: "POV Horror", img: "pov-horror.svg"},
        {name: "Qello Concerts", img: "qello-concerts.svg"},
        {name: "Gaia", img: "gaia.svg"},
        {name: "Plex", img: "plex.png"},
        {name: "Rlaxx", img: "rlaxx.png"},
        {name: "Dove Channel", img: "dove-channel.svg"},
        {name: "FandangoNOW", img: "fandango-now-stacked.svg"},
        {name: "Zuzu", img: "zuzu.png"},
        {name: "Moodbox", img: "moodbox.png"},
        {name: "Caliber", img: "caliber.png"},
        {name: "Pantaflix", img: "pantaflix.svg"},
        {name: "Revry", img: "revry.svg"},
        {name: "ONEHUBTV", img: "onehub-tv.svg"},
        {name: "Millennium TV", img: "millenium-tv.png"},
        {name: "The Roku Channel", img: "roku-channel-vertical-traced.svg"},
        {name: "Amazon Prime Video US", img: "amazon-prime-video-us.svg"},
        {name: "Xumo", img: "xumo.svg"},
        {name: "SocialClubTV", img: "social-club-tv.png"},
        {name: "TubiTV", img: "tubitv.svg"},
        {name: "IMDb TV", img: "imdb-tv.png"},
        {name: "Apple TV App", img: "apple-tv-app.png"},
        {name: "Google TV", img: "google-tv-vertical.svg"},
        {name: "FlexnetTV", img: "flexnet.png"},
        {name: "Hoopla", img: "hoopla.svg"},
        {name: "Kanopy", img: "kanopy.svg"},
        {name: "Overdrive", img: "overdrive.png"},
        {name: "Q0sm", img: "qosm.png"},
        {name: "ConTV", img: "contv.svg"},
        {name: "Christian Cinema", img: "christian-cinema.svg"},
        {name: "TGXLive", img: "tgx-live.png"},
        {name: "GuideDoc", img: "guidedoc.svg"},
        {name: "GayBingeTV", img: "gaybingetv.png"},
        {name: "Conscious Good", img: "conscious-good.svg"},
        {name: "Telus", img: "telus.svg"},
        {name: "Saltflix", img: "saltflix.png"},
        {name: "Vuuzle", img: "vuuzle.png"},
        {name: "PlayNow Media", img: "playnow-media.png"},
        {name: "FreebieTV", img: "freebie-tv.png"},
      ]
    }
  },
]